### PR TITLE
Added LifeBar object

### LINKED ISSUE #10: Implement Life Bar
## Summary:
We will be using a life bar to determine when a player has lost and should be redirected to the game over screen.

In and of itself, the ultimate lose condition of the game if it hits 0.

## Possible Solutions:
Required functions:
- [ ] Constructor (max life)
- [ ] Add Life (amount)
- [ ] Remove Life (amount)

### PR DESCRIPTION
**Pull request by AndyJPL**
## Changes:
Added lifeBar file to objects folder, and added challengeMode folder to assets folder, which now includes lifeBar.png file. Added code to challengeMode.js, to create/draw LifeBar object,

Closes #10 

## How to test this PR:
 Added temporary code to challengeMode.js, which can be uncommented to test functionality using buttons.

## Checklist:
- [x] tested locally
- [x] added tests if needed
- [x] linked the associated ticket
- [x] assigned yourself to this PR

### CODE REVIEW

**Review by rodneybarnes — CHANGES_REQUESTED** [review]
This is sweet! Good work on this, I tested locally and the life bar worked exactly as expected.

Just one change I'd like to request: we'll eventually need to use the life bar to determine whether the player has lost, so I think we'll need another property on here to let us know how much life is left; maybe putting `this.health = 100` in the constructor, and then decreasing/increasing it in the associated methods?

**Comment by AndyJPL** [comment]
Great, thanks @rodneybarnes!  Yes, a "health" instance variable...sorry, I actually meant to bring this up at the last check-in meeting. I did actually originally have a "this.health" instance variable in there, but then I wasn't sure if there was eventually going to be a Character object class, and that the "health" attribute would be more appropriate there, and that class gets values using the .getLifeLevel() method in LifeBar, to inform "health" values, you know? 

But I can definitely implement the changes you've suggested, if you reckon that's the best way!

**Comment by VictorSohier** [comment]
> This is sweet! Good work on this, I tested locally and the life bar worked exactly as expected.
> 
> Just one change I'd like to request: we'll eventually need to use the life bar to determine whether the player has lost, so I think we'll need another property on here to let us know how much life is left; maybe putting `this.health = 100` in the constructor, and then decreasing/increasing it in the associated methods?

Maybe instead of a property, we could use a callback or do something like a ".then()" with promises because we would almost certainly execute code when health hits zero. I am planning on refactoring buttons such that then callback hell may be no more and it could then support other actions such as equivalents to "onhover" or "onfocus".

**Comment by AndyJPL** [comment]
whoops, sorry @VictorSohier .....I pushed in a commit using a "this.health" property, before I saw your comment! But I can look into using a .then() method, for sure.

**Review by VictorSohier — APPROVED** [review]

**Review by rodneybarnes — APPROVED** [review]
Looks great! Awesome work on this 👍

**Comment by AndyJPL** [comment]
> Looks great! Awesome work on this 👍

Ok, thanks a lot Rodney! I was actually still trying to implement promises into this, but maybe when I'm a bit more confident, I will come back to it, and modify it.

**Pull request merged**
